# Generated by Django 4.2.1 on 2023-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(help_text='username', max_length=200, verbose_name='username')),
                ('book_status', models.CharField(choices=[('BORROWED', 'book_unavailable'), ('AVAILABLE', 'book_available')], default='AVAILABLE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='username', max_length=20, verbose_name='username')),
                ('password', models.CharField(help_text='password', max_length=20, verbose_name='password')),
                ('user_type', models.CharField(help_text='user_type', max_length=20, verbose_name='user_type')),
            ],
        ),
    ]
